/**:
  ros__parameters:

    # Topics
    # front_pc_topic: "/luminar_front_points"         
    # left_pc_topic: "/luminar_left_points"           
    # right_pc_topic: "/luminar_right_points"              
    front_pc_topic: "/luminar_front/points"         
    left_pc_topic: "/luminar_left/points"           
    right_pc_topic: "/luminar_right/points"   
    rear_pc_topic: "/luminar_rear/points"   

    merged_pc_topic: "/luminar_merged"    

    # Frames
    front_lidar_frame: "luminar_front"
    right_lidar_frame: "luminar_right"
    left_lidar_frame: "luminar_left"
    rear_lidar_frame: "luminar_rear"

    pub_freq: 13.0
    crop_size: 2.0
    voxel_res: 0.2
    cutoff_dist: 120.0
    cutoff_elevation: 0.011
